# Generated by Django 4.1.4 on 2022-12-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_profile_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='thread',
        ),
    ]
