# Generated by Django 4.1.4 on 2022-12-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_post_comment_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
