# Generated by Django 4.1.4 on 2022-12-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_thread_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='slug',
        ),
    ]
